### ISSUE TITLE
Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by jameslinimk** [doowb/npm-api#20]
```js
TypeError: Cannot read property 'latest' of undefined
    at Repo.package (/pro/burito/node_modules/npm-api/lib/models/repo.js:49:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Packages: **discord.ts**, **iseven**, **chal**

**Comment by doowb** [comment]
Hi @jameslinimk thanks for the issue.
Will you show an example of how you're using `npm-api` so I can understand the issue better?
This looks like the same issue as #7, but I'm not sure without seeing more code.
